<a href="https://colab.research.google.com/github/XimenaCasti/Deep_Learning_NeuralNetwork/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.


application_cat = application_df.dtypes.index.tolist()
application_df[application_cat].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
type_count = application_df['APPLICATION_TYPE'].value_counts()
type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list (type_count[type_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [55]:
# Look at CLASSIFICATION value counts for binning

classification_type_count = application_df['CLASSIFICATION'].value_counts()
classification_type_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [56]:
# You may find it helpful to look at CLASSIFICATION value counts >1

classifications_to_replace = list(classification_type_count[classification_type_count > 1].index)
classifications_to_replace

['C1000', 'C2000', 'C1200', 'C3000', 'C2100', 'Other', 'C7000']

In [57]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

classifications_to_replace = list(classification_type_count[classification_type_count <300].index)


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [65]:
# Convert categorical data to numeric with `pd.get_dummies`

cat_tonumeric = pd.get_dummies(application_df)
cat_tonumeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [68]:
# Split our preprocessed data into our features and target arrays

X = cat_tonumeric.drop(["IS_SUCCESSFUL"], axis=1)
y = cat_tonumeric["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [76]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [103]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = X_train.shape[1]
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 250

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))


# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 100)               4500

 dense_31 (Dense)            (None, 250)               25250

 dense_32 (Dense)            (None, 1)                 251

=================================================================
Total params: 30001 (117.19 KB)
Trainable params: 30001 (117.19 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [100]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [101]:
# Train the model

fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5733 - accuracy: 0.7195
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5603 - accuracy: 0.7276
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7301
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7290
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7310
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5515 - accuracy: 0.7302
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7313
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7329
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7331
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7334
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7338
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7335
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7338
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7333
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7328
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7342
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7321
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7325
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7335
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7346
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7349
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7343
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7357
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7357
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7358
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7361
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7356
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7366
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7373
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7381
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7375
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7381
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7394
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7377
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7385
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5386 - accuracy: 0.7393
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7389
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7384
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7388
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7391
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7393
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7390
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7386
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7397
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7398
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7389
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7386
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7392
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7395
Epoch 56/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7408
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7396
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7407
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7407
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7404
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7404
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7408
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7409
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7406
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7412
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7411
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7405
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7409
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7408
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7413
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7413
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7407
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7409
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7411
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7418
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7411
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7418
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7413
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7414
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7416
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7415
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7418
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7416
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7416
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7422
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7420
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7417
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7411
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7414
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7417
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7416
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5310 - accuracy: 0.7423
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7427
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7418
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7425
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7420

In [102]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5725 - accuracy: 0.7251 - 430ms/epoch - 2ms/step
Loss: 0.5724639296531677, Accuracy: 0.7251312136650085

In [104]:
# Export our model to HDF5 file
nn.save("Model1.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.